version: '3.8'

services:
  portfolio-web:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-web.rule=Host(`nooridev.com`) || Host(`www.nooridev.com`)"
      - "traefik.http.routers.portfolio-web.entrypoints=websecure"
      - "traefik.http.routers.portfolio-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio-web.loadbalancer.server.port=3000"

  portfolio-api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: unless-stopped
    expose:
      - 5000
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-api.rule=Host(`nooridev.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.portfolio-api.entrypoints=websecure"
      - "traefik.http.routers.portfolio-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio-api.loadbalancer.server.port=5000"

networks:
  traefik_default:
    external: true